# disable autofixing PRs, commenting "pre-commit.ci autofix" on a pull request triggers a autofix
ci:
  autofix_prs: false
# generally speaking we ignore all vendored code as well as tests data
# ignore patches/diffs since slight reformatting can break them
exclude: |
  (?x)^(
    tests/(
      archives |
      index_data |
      test-cran-skeleton |
      test-recipes |
      test-skeleton
    )/ |
    .*\.(patch|diff) |
    versioneer.py |
    conda_build/_version.py
  )
repos:
  # generic verification and formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # standard end of line/end of file cleanup
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # ensure syntaxes are valid
      - id: check-toml
      - id: check-yaml
        exclude: |
          (?x)^(
            recipe/meta\.yaml |
            conda_build/templates/.*\.yaml |
            docs/click/meta\.yaml |
            docs/source/user-guide/tutorials/meta\.yaml
          )
      # catch git merge/rebase problems
      - id: check-merge-conflict
  # Python verification and formatting
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      # auto inject license blurb
      - id: insert-license
        files: \.py$
        args: [--license-filepath, .github/disclaimer.txt, --no-extra-eol]
        exclude: ^conda_build/version.py
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.6.0
    hooks:
      # upgrade standard Python codes
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      # auto sort Python imports
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      # auto format Python codes
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      # auto format Python codes within docstrings
      - id: blacken-docs
        additional_dependencies: [black]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      # lint Python codes
      - id: flake8
