environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tools\\appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Python35_64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python27_64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34_64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python27_32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35_32"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34_32"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %HOME%


install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
  # these correspond to folder naming of miniconda installs on appveyor.  See
  # https://www.appveyor.com/docs/installed-software#python
  - if "%PYTHON_VERSION%" == "3.4" set "BASE_PYTHON_VERSION=3"
  - if "%PYTHON_VERSION%" == "3.5" set "BASE_PYTHON_VERSION=35"
  - if "%PYTHON_ARCH%" == "64" set "ARCH_LABEL=-x64"
  # These are already installed on appveyor.  Update them.
  - set "CONDA_ROOT=C:\Miniconda%BASE_PYTHON_VERSION%%ARCH_LABEL%"
  - set "PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;%PATH%"
  - conda config --set always_yes yes
  - conda update -q conda
  - git clone https://github.com/conda/conda
  - cd conda
  - git checkout 4.0.8
  - python setup.py install
  - cd ../
  - conda info
  - conda update -q --all
  - python -c "import sys; print(sys.version)"
  - python -c "import sys; print(sys.executable)"
  - python -c "import sys; print(sys.prefix)"
  - conda install -q pytest pytest-cov requests pycrypto git anaconda-client
  # test with master of conda
  - git clone https://github.com/conda/conda
  - cd conda && python setup.py install && cd ..
  # this is to ensure dependencies
  - conda install -q conda-build
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - python setup.py install
  - set PATH
  - conda build --version
  - call appveyor\setup_x64.bat
  - copy "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars64.bat" "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64\vcvarsamd64.bat"


# Not a .NET project, we build package in the install step instead
build: false

test_script:
  - set "PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;%PATH%"
  - set PATH
  - py.test --cov conda_build --cov-report xml tests

on_success:
  - pip install codecov
  - codecov --env PYTHON_VERSION
